name: Collect all releases

on:
  workflow_dispatch:
    inputs:
      destination_folder:
        description: 'Choose folder'
        default: '21-22'
        required: true
        type: string
      skip_apk:
        description: 'Do not add apk to artifact'
        required: true
        default: false
        type: boolean
      skip_presentation:
        description: 'Do not add presentation to artifact'
        required: true
        default: false
        type: boolean
      skip_sources:
        description: 'Do not add sources to artifact'
        required: true
        default: false
        type: boolean



jobs:
  get-students-info:
    uses: Vova-SH/SamsungProjects21-22/.github/workflows/get-students-info.yaml@main
    with:
      destination_folder: ${{ inputs.destination_folder }}

  create-artifacts:
    needs: get-students-info
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.get-students-info.outputs.students-project) }}
    uses: Vova-SH/SamsungProjects21-22/.github/workflows/get-last-release.yaml@main
    with:
      student: ${{ matrix.data.folder }}
      repo: ${{ matrix.data.repo }}
      matrix-result-name: release-report
      skip_apk: ${{ inputs.skip_apk }}
      skip_presentation: ${{ inputs.skip_presentation }}
      skip_sources: ${{ inputs.skip_sources }}

  release-result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [create-artifacts]
    outputs:
      result: "${{ steps.report.outputs.result }}"
    steps:
      - name: Get report
        uses: cloudposse/github-action-matrix-outputs-read@0.1.1
        id: report
        with:
          matrix-step-name: release-report
      - name: Show report
        run: echo "${{ steps.report.outputs.result }}"

  build-apk:
    needs: [release-result]
    strategy:
      fail-fast: false
      matrix:
        data: ${{ fromJson(needs.release-result.outputs.result) }}
    uses: Vova-SH/SamsungProjects21-22/.github/workflows/build-apk.yaml@main
    with:
      artifact-name: ${{ matrix.data.key }}
      archive-name: ${{ matrix.data.value }}