name: Get students info from yaml

on:
  workflow_call:
    inputs:
      destination_folder:
        description: 'Choose folder'
        default: '21-22'
        required: true
        type: string
    outputs:
      students-project:
        description: "All students, which have in YAML file"
        value: ${{ jobs.parse-source-file.outputs.students-project }}

    

jobs:
  parse-source-file:
    runs-on: ubuntu-latest
    outputs:
      students-project: ${{ steps.setup_repos.outputs.works }}
    steps:
      - name: Checkout last changes
        uses: actions/checkout@v3.5.2

      - name: Read base information from ${{ inputs.destination_folder }}/info.yaml
        id: setup_repos
        run: |
          JSON=$(yq e -o=json ./${{ inputs.destination_folder }}/info.yaml)
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/''}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "works=${JSON}" >> "$GITHUB_OUTPUT"
      - name: Checking data
        run: echo "${{ steps.setup_repos.outputs.works }}"