name: Download Release For Repos

on:
  workflow_dispatch:

jobs:
  downloaded_repos:
    strategy:
      matrix:
        data: [
          {repo: "Vova-SH/MakeUpYourMind", folder: "Vova"},
          {repo: "Vova-SH/MakeUpYourMind", folder: "Vova2"}
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Copied last release from ${{ matrix.data.repo }}
        id: copied_releases
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ matrix.data.repo }}
          latest: true
          fileName: "*"
          out-file-path: repos/${{ matrix.data.folder }}
          tarBall: false
          zipBall: true

      - name: Save to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.data.folder }}
          path: repos/${{ matrix.data.folder }}/*.zip

  zip_repos:
    needs: downloaded_repos
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R
