name: Download Release For Repos

on:
  workflow_dispatch:

jobs:
  downloaded_repos:
    strategy:
      matrix:
        data: [
          {repo: "Vova-SH/MakeUpYourMind", folder: "Vova"},
          {repo: "GalinaDa/ListOfProduct", folder: "Галина Давыденко"}
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Copied last release from ${{ matrix.data.repo }}
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ matrix.data.repo }}
          latest: true
          fileName: "*"
          out-file-path: repos/${{ matrix.data.folder }}
          tarBall: false
          zipBall: true
          
      - name: Check APK
        id: check_apk
        uses: andstor/file-existence-action@v1
        with:
          files: "repos/${{ matrix.data.folder }}/*.apk"
          
      - name: Check PPT
        id: check_ppt
        uses: andstor/file-existence-action@v1
        with:
          files: "repos/${{ matrix.data.folder }}/*.ppt"
          
      - name: Check PPTX
        id: check_pptx
        uses: andstor/file-existence-action@v1
        with:
          files: "repos/${{ matrix.data.folder }}/*.pptx"
          
      - name: Check PDF
        id: check_pdf
        uses: andstor/file-existence-action@v1
        with:
          files: "repos/${{ matrix.data.folder }}/*.pdf"
        
      - name: Save to artifacts
        if: ${{ steps.check_apk.outputs.files_exists == 'true' && ( steps.check_ppt.outputs.files_exists == 'true' || steps.check_pptx.outputs.files_exists == 'true' || steps.check_pdf.outputs.files_exists == 'true' ) }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.data.folder }}
          path: |
            repos/${{ matrix.data.folder }}/*.ppt
            repos/${{ matrix.data.folder }}/*.pptx
            repos/${{ matrix.data.folder }}/*.pdf
            repos/${{ matrix.data.folder }}/*.apk
            repos/${{ matrix.data.folder }}/*.zip
  zip_repos:
    needs: downloaded_repos
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Structure of downloaded files
        run: ls -R

      - name: Upload all projects
        uses: actions/upload-artifact@v3
        with:
          name: All-Projects
          path: ./**
