name: Download Release For Repos

on:
  workflow_dispatch:

env:
  data: [
    {repo: "Vova-SH/MakeUpYourMind", folder: "Vova"},
    {repo: "Vova-SH/MakeUpYourMind", folder: "Vova2"}
  ]

jobs:
  downloaded_repos:
    strategy:
      matrix:
        data: $data
    runs-on: ubuntu-latest
    steps:
      - name: Copied last release from ${{ matrix.data.repo }}
        id: copied_releases
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ matrix.data.repo }}
          latest: true
          fileName: "*"
          out-file-path: repos/${{ matrix.data.folder }}
          tarBall: false
          zipBall: true

      - name: Save to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: repos/${{ matrix.data.folder }}/*.zip
