name: Download Release For Repos

on:
  workflow_dispatch:

jobs:
  downloaded_repos:
    strategy:
      matrix:
        repositories: ["Vova-SH/MakeUpYourMind"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copied last release from ${{ matrix.repositories }}
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ matrix.repositories }}
          latest: true
          fileName: "*"
          out-file-path: "repos/"${{ matrix.repositories }}
          tarBall: false
          zipBall: true
  create_artifacts:
    needs: downloaded_repos
    runs-on: ubuntu-latest
    steps:
      - name: Save to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: test/*.zip

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,        
          echo test, and deploy your project.
